version: "3.2"

services:

  cloud-ide:
    build:
      context: .
    container_name: cloud-ide
    environment:
      BIND_ADDRESS: cloud-ide
    volumes:
      - type: bind
        source: ./project
        target: /home/project
    ports:
      - "33000:3000"
    restart: "always"