version: "3.2"

services:

  music-server:
    build:
      context: .
    container_name: "music-server"
    volumes:
      - type: "bind"
        source: ~/Musik
        target: /srv/music
    devices:
      - /dev/snd
    network_mode: "host"
    ports:
      - "6600:6600"
      - "6680:6680"